### ISSUE TITLE
Excuse me, how is this tilt effect achieved?

### ISSUE THREAD

**Issue by gaojuanjuan** [RafaelBarbosatec/hidden_drawer_menu#10]
![app2](https://user-images.githubusercontent.com/14133759/55063090-324fc480-50b2-11e9-88d8-6a26ee340475.gif)

**Comment by RafaelBarbosatec** [comment]
Yes, at the moment the perspective effect was disabled by a flutter bug. In the new version, for some reason if you add ClipRRect inside something that will be transformed into perspective a bug occurs (the screen disappears)

**Comment by gaojuanjuan** [comment]
Oh, thank you.
