### ISSUE TITLE
How make a custom menu page?

### ISSUE THREAD

**Issue by DamianRincon** [RafaelBarbosatec/hidden_drawer_menu#14]
I am trying to use the following code:

screenSelectedBuilder: (position) {
          switch(position){
            case 0 : return Page1(); break;
            case 1 : return Page2(); break;
            case 2 : return Page3(); break;
          }
        },
but it marks me error.
I'm guiding myself on the readme

**Comment by RafaelBarbosatec** [comment]
I'm sorry, I forgot to update the README
