### ISSUE TITLE
appBar customisation

### ISSUE THREAD

**Issue by gromdroid** [RafaelBarbosatec/hidden_drawer_menu#2]
I don't know if this is the right place to post this, but I love your plugin and I'm wondering if it's possible to implement more customisation for the appbar. Now it's possible to set the appbar color etc. but this is for all the appbars. Would it be possible to set a different color for every 'screen'? Or would it else be possible to open/close the menu from a standard scaffold appbar?

**Comment by RafaelBarbosatec** [comment]
Glad to know that you liked this menu. I loved your suggestions and with the changes I made recently it will be possible. I'll be looking into adding them.

**Comment by RafaelBarbosatec** [comment]
In version 1.0 this is possible using SimpleHiddenDrawer or AnimatedDrawerContent

**Comment by beagle-barks** [comment]
I also don't know if it's the right place, didn't want to open another issue on this.
I like this menu very much, but I also want to have more control over the AppBar's layout. 

I wish to center out the title, like it's possible with the 'centerTitle' attribute of AppBar.
