### ISSUE TITLE
Keeping each ScreenHiddenDrawer alive? 

### ISSUE THREAD

**Issue by adar2378** [RafaelBarbosatec/hidden_drawer_menu#21]
Each of the ScreenHiddenDrawer is rebuilding each time I change the the screen from the drawer. How can stop rebuilding it? Tried to include automatickeepalivemixin in each of the screens but not working!

**Comment by elisar4** [comment]
Solved the issue by using IndexedStack like this:
```dart
return SimpleHiddenDrawer(
   menu: Menu(),
   screenSelectedBuilder: (position, controller) {
      return IndexedStack(
         index: position,
         children: <Widget>[
            HomePage(onPressed: () { controller.toggle(); }),
            MapPage(onPressed: () { controller.toggle(); }),
         ],
      );
   },
);
```

**Comment by RafaelBarbosatec** [comment]
In the moment the soluction submited for @elisar4 looks good.
I'm going to improve soon!
