### ISSUE TITLE
Touch target for dragging screen back is too small

### ISSUE THREAD

**Issue by hinterlandsupplyco** [RafaelBarbosatec/hidden_drawer_menu#34]
The touch target on the selected screen when the menu is open is waaaaay to small. It needs to be smaller and / or tapping anywhere on the selected screen should close the menu.

**Comment by hinterlandsupplyco** [comment]
I feel like #25 from @yasseroj would solve this? Can that get reviewed? @RafaelBarbosatec

**Comment by RafaelBarbosatec** [comment]
Sorry for the delay. Resolving conflicts I will be doing merge.

**Comment by RafaelBarbosatec** [comment]
functionality available in the version 2.0.0.
