### ISSUE TITLE
How to pass controller toggle to another file?

### ISSUE THREAD

**Issue by StefanTFletcher** [RafaelBarbosatec/hidden_drawer_menu#35]
Hi, 

I want to pass my controller toggle (which is in the example custom menu script,) to another file so it will open and close my sliding menu.

Effectively I have disabled the app bar from being forced onto every screen it goes to, but I still want the feature of toggling the controller from the app bar

How would I be able to pass this to my second script?

Can post code below if anyone needs it! 

Thanks
@RafaelBarbosatec

**Comment by EbrahimMosaaed** [comment]
I want to do the same ,did you find any solution plz?

**Comment by EbrahimMosaaed** [comment]
> Hi,
> 
> I want to pass my controller toggle (which is in the example custom menu script,) to another file so it will open and close my sliding menu.
> 
> Effectively I have disabled the app bar from being forced onto every screen it goes to, but I still want the feature of toggling the controller from the app bar
> 
> How would I be able to pass this to my second script?
> 
> Can post code below if anyone needs it!
> 
> Thanks
> @RafaelBarbosatec

I want to do the same ,did you find any solution plz?

**Comment by RafaelBarbosatec** [comment]
Hi StefanTFletcher! have you tried that `SimpleHiddenDrawerProvider.of(context).toggle();` ?

**Comment by RafaelBarbosatec** [comment]
in the version 2.0.0 use `SimpleHiddenDrawerController.of(context)` on screens or customized menu
