### ISSUE TITLE
Integration with Maps

### ISSUE THREAD

**Issue by damato3** [RafaelBarbosatec/hidden_drawer_menu#40]
Hi,

I'm trying to integrate a `SimpleHiddenDrawer` widget with a `GoogleMaps` in the main screen.
Problem is that the `GestureDetector` prevents the map to be draggable, i've set the `isDraggable` to false but that doesn't work, the GestureDetector still gets the dragging events.

As a work around, i've altered a bit the `animated_drawer_content.dart` file to avoid the GestureDetector catching dragging events if the `isDraggable` flag is true.

Do you have another solution for this?

Thank you.

**Comment by damato3** [comment]
Anyone interested on my solution check PR https://github.com/RafaelBarbosatec/hidden_drawer_menu/pull/41

**Comment by RafaelBarbosatec** [comment]
Thanks for contribution!

**Comment by damato3** [comment]
Hi @RafaelBarbosatec,

Thanks for merging my PR, however after a research i found another way to achieve what i was trying to do without making changes to the library.
We just need to set the `gestureRecognizers` property in the `GoogleMap` widget, like this:
```
GoogleMap(
  gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
    Factory<OneSequenceGestureRecognizer>(() => EagerGestureRecognizer())
  ].toSet(),
  ...
),
```
the `EagerGestureRecognizer` will catch Map dragger events as well as other events.
Still, the PR can help with other cases where different widgets are claiming gesture events.
