### ISSUE TITLE
Page is disappearing using perspective and latest Flutter version.

### ISSUE THREAD

**Issue by FCMHUB** [RafaelBarbosatec/hidden_drawer_menu#5]
Thanks for this awesome package!

Page disapears on latest Flutter version.

Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale pt-BR)
hidden_drawer_menu 0.5.0

Simulate:
Just update flutter (Beta channel) and set 'enablePerspective' to true (version 0.5.0).

![screenshot_1549048651](https://user-images.githubusercontent.com/33237325/52144653-185fab80-2646-11e9-9d1d-fc80504fc519.png)

**Comment by RafaelBarbosatec** [comment]
Thanks for issue. I'll be reviewing and correcting.

**Comment by RafaelBarbosatec** [comment]
This feature has been removed by conflict with ClipRect p
